name = "dir_to_graphviz"
description = "Print directories as a graphviz file."
version = "0.1.0-dev"

authors = ["Paul Jarrett"]
maintainers = ["Paul Jarrett <jarrett.paul.young@gmail.com>"]
maintainers-logins = ["pyjarrett"]
licenses = "Apache-2.0"
website = ""
tags = ["dir", "graph"]

executables = ["dir_to_graphviz"]

[[depends-on]]
dir_iterators = "~0.0.4"
